# Generated by Django 3.2.4 on 2021-08-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crud',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=40)),
                ('last', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'crud',
            },
        ),
    ]
