# Generated by Django 3.2.4 on 2021-08-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crud',
            new_name='use',
        ),
        migrations.AlterModelTable(
            name='use',
            table='use',
        ),
    ]
