# Generated by Django 3.2.4 on 2021-08-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210804_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=40)),
                ('last', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('dob', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='use',
        ),
    ]
